version: '3.8'

services:
  app:
    build: .
    container_name: shortener_app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=shortener
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    command: /bin/sh -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000"

  mysql:
    image: mysql:8.0
    container_name: shortener_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shortener
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: shortener_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
